import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

export function getOteWritingSubmissionFileBase(submissionId) {
  return `ote-writing-${submissionId || "submission"}`;
}

function safeText(value) {
  return String(value || "").trim();
}

function bodyParagraph(text, options = {}) {
  return new Paragraph({
    text: safeText(text) || "(no answer)",
    spacing: { after: 140 },
    ...options,
  });
}

function headingParagraph(text, options = {}) {
  return new Paragraph({
    text,
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 120 },
    ...options,
  });
}

function answerBlock(text) {
  return new Paragraph({
    children: [
      new TextRun({
        text: safeText(text) || "(no answer)",
        italics: !safeText(text),
      }),
    ],
    spacing: { after: 220 },
    border: {
      left: { color: "D6DAE2", size: 8, space: 12 },
    },
    indent: { left: 240 },
  });
}

export function buildOteWritingSubmissionText({ submissionId, submission, mock }) {
  const task2Choice = submission.task2Choice || "essay";
  const task2 = mock.task2.options[task2Choice];
  return [
    `${mock.title}`,
    `Submission ID: ${submissionId || "local"}`,
    `Part 2 option: ${task2.title}`,
    "",
    `Task 1: Email (${submission.counts?.task1 ?? 0} words)`,
    submission.answers?.task1 || "(no answer)",
    "",
    `Task 2: ${task2.title} (${submission.counts?.[task2Choice] ?? 0} words)`,
    submission.answers?.[task2Choice] || "(no answer)",
  ].join("\n");
}

export async function downloadOteWritingSubmissionDocx({ submissionId, submission, mock }) {
  const task2Choice = submission.task2Choice || "essay";
  const task2 = mock.task2.options[task2Choice];

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: "Aptos", size: 24 },
          paragraph: { spacing: { line: 276 } },
        },
      },
      paragraphStyles: [
        {
          id: "TitleStyle",
          name: "Title Style",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { font: "Aptos", size: 32, bold: true },
          paragraph: { spacing: { after: 240 } },
        },
      ],
    },
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            text: `Oxford Test of English Practice - Writing: ${mock.title}`,
            style: "TitleStyle",
          }),
          bodyParagraph(`Submission ID: ${submissionId || "local"}`),
          bodyParagraph(`Part 2 option: ${task2.title}`),
          headingParagraph("Part 1: Email"),
          bodyParagraph(mock.task1.setup),
          ...mock.task1.email.prompts.flatMap((prompt, index) => [
            new Paragraph({
              children: [new TextRun({ text: `${index + 1}. ${prompt.question}`, bold: true })],
              spacing: { after: 80 },
            }),
            bodyParagraph(prompt.note),
          ]),
          bodyParagraph(`Word count: ${submission.counts?.task1 ?? 0}`),
          answerBlock(submission.answers?.task1),
          headingParagraph(`Part 2: ${task2.title}`, { pageBreakBefore: true }),
          bodyParagraph(task2.context),
          bodyParagraph(task2.prompt),
          bodyParagraph(`Word count: ${submission.counts?.[task2Choice] ?? 0}`),
          answerBlock(submission.answers?.[task2Choice]),
          new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [
              new TextRun({
                text: `Generated by Seif OTE Trainer`,
                italics: true,
              }),
            ],
            spacing: { before: 300 },
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${getOteWritingSubmissionFileBase(submissionId)}.docx`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

export function downloadOteWritingSubmissionText({ submissionId, submission, mock }) {
  const blob = new Blob([buildOteWritingSubmissionText({ submissionId, submission, mock })], {
    type: "text/plain;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${getOteWritingSubmissionFileBase(submissionId)}.txt`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 500);
}
