import { Images, MessageCircleQuestion, Presentation, UserRound } from "lucide-react";

export const APTIS_SPEAKING_PARTS = [
  {
    number: "1",
    label: "Part 1",
    title: "Personal Questions",
    copy: "Answer three short questions about yourself, your interests and your experiences.",
    format: "3 questions",
    timing: "30 seconds each",
    icon: UserRound,
    menuSummary: "Strategy guide + exam practice",
    training: [
      {
        id: "part1-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 1 Strategy Guide",
        copy: "Learn how to answer directly, add useful detail and keep speaking for the available time.",
        path: "/speaking/parts/1/strategy-guide",
        demoAccess: "demo",
      },
    ],
    practice: {
      id: "part1-practice",
      eyebrow: "Exam practice",
      title: "Part 1 Task Library",
      copy: "Practise complete sets of three personal questions with timed recording and feedback.",
      path: "/speaking/part1",
      demoAccess: "demo",
    },
  },
  {
    number: "2",
    label: "Part 2",
    title: "Describe a Photograph",
    copy: "Describe one photograph, then answer questions about your experience and opinions.",
    format: "1 photo · 3 questions",
    timing: "45 seconds each",
    icon: Images,
    menuSummary: "Strategy guide + shared picture guide + exam practice",
    training: [
      {
        id: "part2-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 2 Strategy Guide",
        copy: "Learn how to organise a photo description and develop the two follow-up answers.",
        path: "/speaking/parts/2/strategy-guide",
        demoAccess: "demo",
      },
      {
        id: "part2-photo-guide",
        eyebrow: "Guided practice · Parts 2 & 3",
        title: "Describing Pictures",
        copy: "Build the picture-description skills used here and again when describing and comparing pictures in Part 3.",
        path: "/speaking/photo-guide",
        demoAccess: "locked",
        badge: "Also useful for Part 3",
      },
    ],
    practice: {
      id: "part2-practice",
      eyebrow: "Exam practice",
      title: "Part 2 Task Library",
      copy: "Describe a photograph and answer two related questions in complete timed tasks.",
      path: "/speaking/part2",
      demoAccess: "demo",
    },
  },
  {
    number: "3",
    label: "Part 3",
    title: "Describe and Compare",
    copy: "Describe and compare two photographs, then discuss the topic in more detail.",
    format: "2 photos · 3 questions",
    timing: "45 seconds each",
    icon: MessageCircleQuestion,
    menuSummary: "Strategy guide + comparison training + exam practice",
    related: {
      eyebrow: "Shared guide · Parts 2 & 3",
      title: "Need help describing the pictures first?",
      copy: "The Describing Pictures activity is kept in Part 2 because those same foundation skills are used in both parts.",
      path: "/speaking/parts/2",
      cta: "Find it in Part 2",
    },
    training: [
      {
        id: "part3-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 3 Strategy Guide",
        copy: "Learn how to balance description, comparison and discussion across the three questions.",
        path: "/speaking/parts/3/strategy-guide",
        demoAccess: "locked",
      },
      {
        id: "part3-comparing-guide",
        eyebrow: "Guided practice",
        title: "Comparing Pictures",
        copy: "Explore useful comparison language and practise expressing similarities and differences clearly.",
        path: "/speaking/part3-comparing",
        demoAccess: "locked",
      },
    ],
    practice: {
      id: "part3-practice",
      eyebrow: "Exam practice",
      title: "Part 3 Task Library",
      copy: "Complete timed picture-comparison tasks and receive focused feedback on your responses.",
      path: "/speaking/part3",
      demoAccess: "demo",
    },
  },
  {
    number: "4",
    label: "Part 4",
    title: "Presentation and Discussion",
    copy: "Prepare and give a two-minute response that brings together three questions on one topic.",
    format: "3 linked questions",
    timing: "1 min prep · 2 min talk",
    icon: Presentation,
    menuSummary: "Strategy guide + exam practice",
    training: [
      {
        id: "part4-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 4 Strategy Guide",
        copy: "Learn how to use the preparation minute, organise one complete response and cover all three questions.",
        path: "/speaking/parts/4/strategy-guide",
        demoAccess: "locked",
      },
    ],
    practice: {
      id: "part4-practice",
      eyebrow: "Exam practice",
      title: "Part 4 Task Library",
      copy: "Plan for one minute, then record a complete two-minute response to all three questions.",
      path: "/speaking/part4",
      demoAccess: "demo",
    },
  },
];

export function getAptisSpeakingPart(number) {
  return APTIS_SPEAKING_PARTS.find((part) => part.number === String(number));
}
