import { BookOpen, FileText, ListOrdered, Users } from "lucide-react";
import { READING_PART2_STANDARD_TASK_IDS } from "./part2Tasks.js";

export const APTIS_READING_PARTS = [
  {
    number: "1",
    label: "Part 1",
    title: "Word Choices",
    copy: "Choose the best word for each gap in a short informal message.",
    format: "5 word choices",
    timing: "3 minutes",
    icon: FileText,
    menuSummary: "Strategy guide + exam practice",
    taskIds: ["cinema-plan", "class-homework", "cafe-meeting", "doctor-appointment", "weekend-trip", "birthday-present"],
    training: [
      {
        id: "part1-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Sentence Comprehension Strategy",
        copy: "Understand each sentence, compare all three options and check that your answer makes sense.",
        path: "/reading/parts/1/strategy-guide",
        demoAccess: "demo",
        progressId: "part1-strategy-guide",
      },
    ],
    practice: {
      id: "part1-practice",
      eyebrow: "Exam practice",
      title: "Part 1 Task Library",
      copy: "Complete exam-style word-choice tasks with feedback and suggested timing.",
      path: "/reading/part1",
      demoAccess: "demo",
    },
  },
  {
    number: "2",
    label: "Part 2",
    title: "Sentence Order",
    copy: "Reorder sentences to build a clear, cohesive short text.",
    format: "2 texts in the exam",
    timing: "3:30 per text",
    icon: ListOrdered,
    menuSummary: "Strategy guide + guided training + exam practice",
    taskIds: READING_PART2_STANDARD_TASK_IDS,
    training: [
      {
        id: "part2-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Text Cohesion Strategy",
        copy: "Follow references, linking words and connected ideas to build the text in small chains.",
        path: "/reading/parts/2/strategy-guide",
        demoAccess: "demo",
        progressId: "part2-strategy-guide",
      },
      {
        id: "part2-guide",
        eyebrow: "Guided practice",
        title: "Explore Cohesive Clues",
        copy: "Reveal the links inside two short texts, then drag the sentences into the correct order.",
        path: "/reading/part2-guide",
        demoAccess: "demo",
        progressId: "part2-guide",
      },
    ],
    practice: {
      id: "part2-practice",
      eyebrow: "Exam practice",
      title: "Part 2 Task Library",
      copy: "Reorder complete exam-style texts and check each position.",
      path: "/reading/part2",
      demoAccess: "demo",
    },
  },
  {
    number: "3",
    label: "Part 3",
    title: "Matching Opinions",
    copy: "Read four comments and decide which person expresses each idea.",
    format: "7 opinion matches",
    timing: "10 minutes",
    icon: Users,
    menuSummary: "Strategy guide + guided training + exam practice",
    taskIds: ["fitness-trackers", "food-delivery-apps", "learning-online", "exercising-with-others", "remote-work"],
    training: [
      {
        id: "part3-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Opinion Matching Strategy",
        copy: "Analyse the seven statements first, then read one person at a time and prove every match.",
        path: "/reading/parts/3/strategy-guide",
        demoAccess: "locked",
        progressId: "part3-strategy-guide",
      },
      {
        id: "part3-strategy",
        eyebrow: "Guided training",
        title: "Match the Idea, Not Just the Words",
        copy: "Decode every question, paraphrase it and prove the best match with complete evidence.",
        path: "/reading/part3-strategy",
        demoAccess: "locked",
        progressId: "part3-strategy",
      },
    ],
    practice: {
      id: "part3-practice",
      eyebrow: "Exam practice",
      title: "Part 3 Task Library",
      copy: "Complete matching-opinion tasks with evidence and detailed explanations.",
      path: "/reading/part3",
      demoAccess: "locked",
    },
  },
  {
    number: "4",
    label: "Part 4",
    title: "Heading Matching",
    copy: "Match headings to the paragraphs of a longer text, with one extra heading.",
    format: "7 paragraph matches",
    timing: "15 minutes",
    icon: BookOpen,
    menuSummary: "Strategy guide + exam practice",
    taskIds: ["yawning", "music-consumer-behaviour"],
    training: [
      {
        id: "part4-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Long Text Comprehension Strategy",
        copy: "Summarise each paragraph’s main idea, compare the headings and use elimination carefully.",
        path: "/reading/parts/4/strategy-guide",
        demoAccess: "demo",
        progressId: "part4-strategy-guide",
      },
    ],
    practice: {
      id: "part4-practice",
      eyebrow: "Exam practice",
      title: "Part 4 Task Library",
      copy: "Complete heading-matching tasks with paragraph-level feedback.",
      path: "/reading/part4",
      demoAccess: "demo",
    },
  },
];

export function getAptisReadingPart(number) {
  return APTIS_READING_PARTS.find((part) => part.number === String(number));
}
