import { BookOpen, FileText, ListOrdered, Users } from "lucide-react";

export const APTIS_READING_PARTS = [
  {
    number: "1",
    label: "Part 1",
    title: "Word Choices",
    copy: "Choose the best word for each gap in a short informal message.",
    format: "5 word choices",
    timing: "3 minutes",
    icon: FileText,
    menuSummary: "Exam practice available",
    taskIds: ["cinema-plan", "class-homework", "cafe-meeting", "doctor-appointment", "weekend-trip", "birthday-present"],
    training: [
      {
        id: "part1-strategy",
        eyebrow: "Strategy guide",
        title: "Part 1 Strategy Guide",
        copy: "Learn how to use grammar, collocation and the meaning of the whole message to choose each word.",
        status: "coming-soon",
      },
    ],
    practice: {
      id: "part1-practice",
      eyebrow: "Exam practice",
      title: "Part 1 Task Library",
      copy: "Complete exam-style word-choice tasks with feedback and suggested timing.",
      path: "/reading/part1",
      demoAccess: "demo",
    },
  },
  {
    number: "2",
    label: "Part 2",
    title: "Sentence Order",
    copy: "Reorder sentences to build a clear, cohesive short text.",
    format: "2 texts in the exam",
    timing: "3:30 per text",
    icon: ListOrdered,
    menuSummary: "Guide + exam practice",
    taskIds: [
      "cycling-lanes__t1",
      "ebooks__t1",
      "helen-graves__t1",
      "film-festival__t1",
      "remote-work__t1",
      "plastic-reduction__t1",
      "plastic-free-school__t1",
      "olive-oil-production__t1",
      "sports-centre-opening__t1",
      "traditional-kimchi-making__t1",
      "city-infrastructure__t1",
    ],
    training: [
      {
        id: "part2-guide",
        eyebrow: "Strategy guide",
        title: "Sentence Order Guide",
        copy: "Spot references, linking language and other cohesive clues before rebuilding the text.",
        path: "/reading/part2-guide",
        demoAccess: "demo",
        progressId: "part2-guide",
      },
    ],
    practice: {
      id: "part2-practice",
      eyebrow: "Exam practice",
      title: "Part 2 Task Library",
      copy: "Reorder complete exam-style texts and check each position.",
      path: "/reading/part2",
      demoAccess: "demo",
    },
  },
  {
    number: "3",
    label: "Part 3",
    title: "Matching Opinions",
    copy: "Read four comments and decide which person expresses each idea.",
    format: "7 opinion matches",
    timing: "10 minutes",
    icon: Users,
    menuSummary: "Guided training + exam practice",
    taskIds: ["fitness-trackers", "food-delivery-apps", "learning-online", "exercising-with-others", "remote-work"],
    training: [
      {
        id: "part3-strategy",
        eyebrow: "Guided training",
        title: "Match the Idea, Not Just the Words",
        copy: "Decode every question, paraphrase it and prove the best match with complete evidence.",
        path: "/reading/part3-strategy",
        demoAccess: "locked",
        progressId: "part3-strategy",
      },
    ],
    practice: {
      id: "part3-practice",
      eyebrow: "Exam practice",
      title: "Part 3 Task Library",
      copy: "Complete matching-opinion tasks with evidence and detailed explanations.",
      path: "/reading/part3",
      demoAccess: "locked",
    },
  },
  {
    number: "4",
    label: "Part 4",
    title: "Heading Matching",
    copy: "Match headings to the paragraphs of a longer text, with one extra heading.",
    format: "7 paragraph matches",
    timing: "15 minutes",
    icon: BookOpen,
    menuSummary: "Exam practice available",
    taskIds: ["yawning", "music-consumer-behaviour"],
    training: [
      {
        id: "part4-strategy",
        eyebrow: "Strategy guide",
        title: "Part 4 Strategy Guide",
        copy: "Learn to identify paragraph purpose, separate main ideas from details and reject broad distractors.",
        status: "coming-soon",
      },
    ],
    practice: {
      id: "part4-practice",
      eyebrow: "Exam practice",
      title: "Part 4 Task Library",
      copy: "Complete heading-matching tasks with paragraph-level feedback.",
      path: "/reading/part4",
      demoAccess: "demo",
    },
  },
];

export function getAptisReadingPart(number) {
  return APTIS_READING_PARTS.find((part) => part.number === String(number));
}
