// Aptis Listening Mock 1, Questions 1–5. Authored tasks and recordings supplied by the user.
export const A1_FIRST_FIVE_QUESTIONS = [
  {
    id: "q1",
    number: 1,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Jamie’s message for Alex.",
    audioSrc: "/audio/listening/mock-1/complete/q01.mp3",
    items: [{
      id: "main",
      prompt: "Who has Alex’s ticket?",
      options: ["Kate", "Grace", "Claire"],
      answer: "A",
    }],
    script: "Hi Alex, it’s Jamie. I can’t come to the club tonight, but your ticket is safe. Grace will be working at the front desk, so ask her if you need help when you arrive. The person with your ticket has short brown hair and a green coat, and she knows your name. It’s my friend Kate, so look for her near the entrance. I hope you enjoy the music. Call me when you get home.",
  },
  {
    id: "q2",
    number: 2,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Daniel’s message for Maria.",
    audioSrc: "/audio/listening/mock-1/complete/q02.mp3",
    items: [{
      id: "main",
      prompt: "When can Maria collect her parcel?",
      options: ["7.15", "8.15", "7.45"],
      answer: "C",
    }],
    script: "Hi Maria, it’s Daniel from next door. Your parcel is at my house. I’m going out this evening, and I won’t be home at quarter past seven. I should be back later, at quarter to eight. You can come over then and collect it. Please knock loudly because I may be in the kitchen and the bell isn’t working. The box is quite heavy, so you may want some help. See you later.",
  },
  {
    id: "q3",
    number: 3,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Rick’s message for Paula.",
    audioSrc: "/audio/listening/mock-1/complete/q03.mp3",
    items: [{
      id: "main",
      prompt: "Where should Paula meet Rick?",
      options: ["Kitchen", "Office", "Garden"],
      answer: "B",
    }],
    script: "Hi Paula, it’s Rick. I’m at work now, and I have the papers for you. I’m going to get a coffee from the kitchen in a minute, but please don’t look for me there. When you arrive, meet me in the office. I’ll be sitting near the big window. I need to ask you something about tomorrow’s work before we go home. It will only take a few minutes. See you soon.",
  },
  {
    id: "q4",
    number: 4,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Dad’s message for Leo.",
    audioSrc: "/audio/listening/mock-1/complete/q04.mp3",
    items: [{
      id: "main",
      prompt: "What should Leo buy?",
      options: ["Carrots", "Tomatoes", "Potatoes"],
      answer: "A",
    }],
    script: "Hi Leo, it’s Dad. I’m making dinner, but I need one more thing. We already have plenty of potatoes, so don’t buy any more. Could you get some carrots on your way home instead? A small bag is enough. Put them on the kitchen table when you come in. I’m busy with the food, so I may not hear the door. Thanks a lot, and see you soon.",
  },
  {
    id: "q5",
    number: 5,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Nadia’s message for Sara.",
    audioSrc: "/audio/listening/mock-1/complete/q05.mp3",
    items: [{
      id: "main",
      prompt: "Which bus should Sara take?",
      options: ["6", "16", "60"],
      answer: "B",
    }],
    script: "Hi Sara, it’s Nadia. I’m waiting for you near the town centre. Don’t take bus sixty because it goes the long way around. Take bus sixteen from outside your house and get off near the river. I’ll be there in my red jacket, so you can see me easily. The journey is quite short, and you can pay on the bus. Send me a message when you get on. See you soon.",
  },
];
