// Aptis Listening Mock 1, Questions 6–10. Authored tasks and recordings supplied by the user.
export const A2_QUESTIONS_SIX_TO_TEN = [
  {
    id: "q6",
    number: 6,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to two friends discussing their journey.",
    audioSrc: "/audio/listening/mock-1/complete/q06.mp3",
    items: [{
      id: "main",
      prompt: "How will they travel?",
      options: ["Bus", "Train", "Car"],
      answer: "B",
    }],
    script: [
      { speaker: "Woman", text: "How should we get to the concert? We could take the bus from the town centre." },
      { speaker: "Man", text: "The bus is cheap, but it stops everywhere. I can use the car, although parking near the concert is difficult." },
      { speaker: "Woman", text: "The train is faster, and the station is only a short walk away." },
      { speaker: "Man", text: "The concert begins soon after work, so we cannot be late. Let’s go by train, then. I’ll meet you outside the station." },
    ],
  },
  {
    id: "q7",
    number: 7,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to a customer ordering lunch.",
    audioSrc: "/audio/listening/mock-1/complete/q07.mp3",
    items: [{
      id: "main",
      prompt: "Why does she want something light?",
      options: ["She is going back to work", "She had soup yesterday", "The sandwich is large"],
      answer: "A",
    }],
    script: [
      { speaker: "Man", text: "Are you ready to order? The soup is very popular today." },
      { speaker: "Woman", text: "I had soup yesterday. I was thinking about the sandwich, but it looks rather large." },
      { speaker: "Man", text: "The salad is lighter, and it comes with bread if you want it." },
      { speaker: "Woman", text: "I don’t want anything too heavy because I’m going back to work. I’ll have the salad, please, but without the bread. Could I have some water as well?" },
      { speaker: "Man", text: "Of course." },
    ],
  },
  {
    id: "q8",
    number: 8,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to Laura’s message for Dan.",
    audioSrc: "/audio/listening/mock-1/complete/q08.mp3",
    items: [{
      id: "main",
      prompt: "Where should Dan meet Laura?",
      options: ["Reception", "Café", "Library"],
      answer: "A",
    }],
    script: "Hi Dan, it’s Laura. I’m calling about the course tomorrow. We usually meet in the library, but another group is using it. The café is open, although it will be busy at that time. Let’s meet at reception instead. It is just inside the main door, so we can find each other easily. We can choose somewhere quiet to sit after that. Please bring the course notes with you.",
  },
  {
    id: "q9",
    number: 9,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to a customer choosing a jacket.",
    audioSrc: "/audio/listening/mock-1/complete/q09.mp3",
    items: [{
      id: "main",
      prompt: "Which jacket is too small?",
      options: ["Green jacket", "Blue jacket", "Black jacket"],
      answer: "B",
    }],
    script: [
      { speaker: "Man", text: "How about this blue jacket? It’s in the sale." },
      { speaker: "Woman", text: "I like the blue jacket, but it’s too small. The green jacket fits well, although the colour is a bit bright for work." },
      { speaker: "Man", text: "We have the same style in black. It also has some useful inside pockets. Would you like to try the black jacket?" },
      { speaker: "Woman", text: "Yes, this one is comfortable and the colour is better. I’ll take it." },
    ],
  },
  {
    id: "q10",
    number: 10,
    type: "multiple-choice",
    part: 1,
    prompt: "Listen to two people discussing a picnic.",
    audioSrc: "/audio/listening/mock-1/complete/q10.mp3",
    items: [{
      id: "main",
      prompt: "Who is bringing the cake?",
      options: ["Oliver", "Sophie", "Mia"],
      answer: "C",
    }],
    script: [
      { speaker: "Woman", text: "Is everything ready for the picnic on Saturday?" },
      { speaker: "Man", text: "Nearly. Oliver is bringing the drinks, and Sophie said she can bring some plates and cups." },
      { speaker: "Woman", text: "What about the food?" },
      { speaker: "Man", text: "I’m making sandwiches in the morning. Mia is bringing the cake because she has a good bakery near her house." },
      { speaker: "Woman", text: "Great. I’ll bring some fruit as well, and we should have enough for everyone. I just hope the weather stays dry." },
    ],
  },
];
