import { Mail, MessagesSquare, PencilLine, TextCursorInput } from "lucide-react";

export const APTIS_WRITING_PARTS = [
  {
    number: "1",
    label: "Part 1",
    title: "Short Answers",
    copy: "Answer five personal questions using individual words or very short phrases.",
    format: "5 questions",
    response: "1–5 words each",
    icon: PencilLine,
    menuSummary: "Strategy guide + guided practice + exam practice",
    training: [
      {
        id: "part1-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 1 Strategy Guide",
        copy: "Learn a reliable method for giving short, accurate answers without adding unnecessary language.",
        path: "/writing/parts/1/strategy-guide",
        demoAccess: "demo",
      },
      {
        id: "part1-short-answer-workshop",
        eyebrow: "Guided practice",
        title: "Short-Answer Workshop",
        copy: "Trim overlong answers, correct common mistakes and compare your responses with clear models.",
        path: "/writing/part1-guide",
        demoAccess: "locked",
      },
    ],
    practice: {
      id: "part1-practice",
      eyebrow: "Exam practice",
      title: "Part 1 Task Library",
      copy: "Answer exam-style personal questions and receive focused feedback on clarity and accuracy.",
      path: "/writing/part1",
      demoAccess: "demo",
    },
  },
  {
    number: "2",
    label: "Part 2",
    title: "Short Text",
    copy: "Write a short response to a form question using complete, relevant sentences.",
    format: "1 response",
    response: "20–30 words",
    icon: TextCursorInput,
    menuSummary: "Strategy guide + exam practice",
    training: [
      {
        id: "part2-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 2 Strategy Guide",
        copy: "Learn how to answer every part, connect a few clear sentences and manage the suggested word range.",
        path: "/writing/parts/2/strategy-guide",
        demoAccess: "demo",
      },
    ],
    practice: {
      id: "part2-practice",
      eyebrow: "Exam practice",
      title: "Part 2 Task Library",
      copy: "Write complete short-text responses and receive feedback on task achievement and language.",
      path: "/writing/part2",
      demoAccess: "demo",
    },
  },
  {
    number: "3",
    label: "Part 3",
    title: "Three Online Responses",
    copy: "Reply naturally to three messages in an online social or discussion setting.",
    format: "3 responses",
    response: "30–40 words each",
    icon: MessagesSquare,
    menuSummary: "Strategy guide + exam practice",
    training: [
      {
        id: "part3-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 3 Strategy Guide",
        copy: "Learn how to respond fully, add useful detail and keep each answer natural and well organised.",
        path: "/writing/parts/3/strategy-guide",
        demoAccess: "locked",
      },
    ],
    practice: {
      id: "part3-practice",
      eyebrow: "Exam practice",
      title: "Part 3 Task Library",
      copy: "Respond to three online questions and receive detailed feedback on content and language.",
      path: "/writing/part3",
      demoAccess: "demo",
    },
  },
  {
    number: "4",
    label: "Part 4",
    title: "Formal and Informal Emails",
    copy: "Respond to one situation by writing an informal email and a longer formal email.",
    format: "2 emails",
    response: "40–50 + 120–150 words",
    icon: Mail,
    menuSummary: "Strategy guide + guided activities + exam practice",
    training: [
      {
        id: "part4-strategy-guide",
        eyebrow: "Strategy guide",
        title: "Part 4 Strategy Guide",
        copy: "Learn how to plan both emails, cover every content point and adapt your register to each reader.",
        path: "/writing/parts/4/strategy-guide",
        demoAccess: "locked",
      },
      {
        id: "part4-email-overview",
        eyebrow: "Guided overview",
        title: "Explore the Part 4 Task",
        copy: "Review the email format, timing, assessment focus and the key skills needed for both messages.",
        path: "/writing/part4-guide",
        demoAccess: "locked",
      },
      {
        id: "part4-register-tone",
        eyebrow: "Guided practice",
        title: "Register & Tone",
        copy: "Classify formal and informal language, then rewrite expressions for the correct audience.",
        path: "/writing/part4-register",
        demoAccess: "locked",
      },
    ],
    practice: {
      id: "part4-practice",
      eyebrow: "Exam practice",
      title: "Part 4 Task Library",
      copy: "Write both emails in complete exam-style tasks and receive detailed feedback.",
      path: "/writing/part4",
      demoAccess: "demo",
    },
  },
];

export function getAptisWritingPart(number) {
  return APTIS_WRITING_PARTS.find((part) => part.number === String(number));
}
