import React, { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, GripVertical, RotateCcw, X } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import Seo from "../../components/common/Seo.jsx";
import { logOteTrainingCompleted, logOteTrainingStarted } from "../../firebase.js";
import { getSitePath } from "../../siteConfig.js";
import "./styles/ote.css";

const TIME_SECONDS = 11 * 60;
const tasks = {
  "a2-pilot-1": {
    title: "My First Community Garden", heading: "My first community garden",
    sentences: { A: "Some of the other gardeners noticed this and came to speak to me.", B: "Unfortunately, there was no rain that week.", C: "I also collected rainwater in a large container beside my plants.", D: "We decided to have a meal in the garden one evening.", E: "At first, I was worried that I would lose the whole crop.", F: "I am still learning, but I feel much more confident now.", G: "My friend bought a new set of tools from a garden shop." },
    answers: { 1: "A", 2: "B", 3: "C", 4: "D", 5: "E", 6: "F" },
    rationales: { 1: "'This' refers to not knowing where to begin, and 'they' then refers to the other gardeners.", 2: "The lack of rain explains why the unwatered plants became dry.", 3: "'This' in the next sentence refers to collecting rainwater.", 4: "The following sentence explains what everyone brought to the shared meal.", 5: "The writer is worried about losing the lettuce and then looks for a safe solution.", 6: "The writer contrasts being a beginner with now feeling confident enough to help new members." },
    paragraphs: [
      "I live in a flat and do not have a garden of my own. Last spring, a friend told me about a community garden near my home. People share the land and grow fruit, vegetables and flowers together. I decided to join, although I knew very little about gardening.",
      ["On my first Saturday there, everyone seemed busy and I did not know where to begin. ", 1, " They gave me a small area and helped me choose some easy plants."],
      ["I planted tomatoes, beans and lettuce. A few days later, I forgot to water them. ", 2, " When I returned, some of the leaves looked dry, but luckily the plants were still alive."],
      ["After that, I set a reminder on my phone. ", 3, " This made watering much easier, especially during hot weather."],
      ["By the middle of summer, we had more vegetables than we could eat. ", 4, " Everyone brought something they had grown, and we had a wonderful evening together."],
      ["Not everything was easy. Snails began eating my lettuce. ", 5, " I did not want to use strong chemicals, so an older gardener showed me a safe way to protect the plants."],
      ["Now I visit the garden twice a week. ", 6, " Next year, I want to grow strawberries and help new members when they arrive."],
    ],
  },
  "a2-pilot-2": {
    title: "A Weekend Without My Phone", heading: "A weekend without my phone",
    sentences: { A: "Of course, there were no new messages because the phone was not connected.", B: "Without a screen to look at, I paid more attention to everything around me.", C: "Luckily, my cousin had brought a small camera with her.", D: "At first, I expected them to be boring, but I was wrong.", E: "However, I decided not to read my messages immediately.", F: "Now I leave it in another room for one hour every evening.", G: "We had to return home because it started to rain heavily." },
    answers: { 1: "A", 2: "B", 3: "C", 4: "D", 5: "E", 6: "F" },
    rationales: { 1: "The phone has no signal, so checking it produces no new messages.", 2: "Paying greater attention to the surroundings leads to noticing birds, flowers and paths.", 3: "'It' in the following sentence refers to the small camera.", 4: "'Them' refers to the board games, and the next sentence shows the writer enjoyed them.", 5: "Although the signal has returned, the writer chooses to continue the walk before checking messages.", 6: "The writer has developed a new daily habit after learning that time away from the phone is relaxing." },
    paragraphs: [
      "I usually check my phone as soon as I wake up and continue using it throughout the day. Last month, my cousin invited me to spend a weekend in her village. She warned me that the phone signal there was very weak.",
      ["On Saturday morning, I picked up my phone several times without thinking. ", 1, " I soon realised that checking it had become a habit, even when there was nothing to see."],
      ["After breakfast, we went for a long walk through the woods. ", 2, " I noticed birds, flowers and small paths that I might normally have missed."],
      ["I wanted to take some pictures of the view from the hill. ", 3, " We used it to take photos, and I did not need my phone after all."],
      ["That evening, my cousin suggested playing board games with her family. ", 4, " Soon we were laughing so much that I completely forgot about going online."],
      ["The next day, we reached a place where my phone finally had a signal. ", 5, " I wanted to enjoy the rest of the walk before reading my messages."],
      ["When I returned home, I turned my phone on again. I had not missed anything important. ", 6, " It helps me relax and gives me more time to notice what is happening around me."],
    ],
  },
  "b1-pilot-1": {
    title: "My First Market Stall", heading: "My first market stall",
    sentences: { A: "This gives returning customers something new without creating too much extra work.", B: "It seemed safer to start with a small selection and learn what customers actually wanted.", C: "My friends had also promised to visit the market and support me during the day.", D: "But when the market opened, the result was disappointing.", E: "She cut one cake into small pieces and showed me how to offer them.", F: "For a moment, I was worried that she would become angry.", G: "I realised that attractive displays alone were not enough to make a successful stall." },
    answers: { 1: "B", 2: "D", 3: "E", 4: "F", 5: "G", 6: "A" },
    rationales: { 1: "Starting with a small selection explains why the writer chooses only three recipes.", 2: "The writer expected the decorated stall to attract attention, but the result was disappointing; the next sentence explains what happened.", 3: "The neighbouring seller demonstrates how to provide samples before customers taste them.", 4: "The returning customer creates a moment of concern before the writer apologises and resolves the problem.", 5: "The writer reflects on the lessons from the experience before adding further lessons about customers and problems.", 6: "Changing one flavour gives regular customers variety without making preparation too demanding." },
    paragraphs: [
      "When I was at university, I often made cakes for friends. They kept telling me that I should sell them, but I never took the idea seriously. Then our town announced a monthly street market for small local businesses. The cost of a stall was low, so I decided to apply and see what happened.",
      ["The first problem was choosing what to sell. I could make many different cakes, but producing too many kinds would take a lot of time and money. ", 1, " I finally chose three simple recipes that I knew people liked and prepared clear labels showing the ingredients in each one."],
      ["On the morning of the market, I arrived early with twenty boxes of cakes. I had spent hours making signs and decorating the table, so I expected customers to notice me immediately. ", 2, " Most people walked past without even looking, while the busier stalls nearby were already selling food."],
      ["A woman at the next stall suggested offering small free samples. I was worried that I would give away too much, but I decided to try. ", 3, " Soon, several people stopped to taste the cakes and then bought full boxes. Some also asked whether I could make cakes for birthdays."],
      ["By lunchtime, I had sold almost everything. However, one customer returned because a box contained the wrong flavour. ", 4, " I apologised, replaced the box and gave her an extra cake. She left smiling and later sent me a kind message through the market website."],
      ["At the end of the day, I was exhausted but pleased. I had earned some money and learned far more than I expected. ", 5, " I also understood that talking to customers was just as important as making good food, and that small problems could be solved calmly."],
      ["I now have a stall at the market every month. I still prepare only a small range of cakes, but I change one flavour each time. ", 6, " Regular customers often come back to discover what is new, and I now take a few advance orders as well. My business is still small, but I no longer think of it as only a hobby."],
    ],
  },
  "b1-pilot-2": {
    title: "Why Study Breaks Matter", heading: "Why study breaks matter",
    sentences: { A: "This is often a sign that it is time to stop for a few minutes.", B: "For this reason, a break from studying should also be a break from screens.", C: "Some students prefer listening to music because it makes the room feel less quiet.", D: "It is therefore better to work for a reasonable period before stopping.", E: "The change of place can be as useful as the break itself.", F: "The real difficulty may be that they need an explanation rather than more concentration.", G: "A useful routine needs to include enough time for both work and rest." },
    answers: { 1: "A", 2: "B", 3: "D", 4: "E", 5: "F", 6: "G" },
    rationales: { 1: "Reduced attention and missed mistakes indicate that a break may be necessary.", 2: "Checking messages introduces more information, so a useful break should avoid screens.", 3: "Stopping too frequently prevents proper concentration, so students should work for a reasonable period first.", 4: "Leaving the study space for a walk makes a change of place useful as well as the break itself.", 5: "If the task itself is unclear, the student needs an explanation before the recommendation to ask for help.", 6: "The conclusion contrasts working too long with resting too often, so a routine needs time for both." },
    paragraphs: [
      "Many students believe that the best way to finish an important piece of work is to continue without stopping. They may sit at a desk for several hours, even when they are tired and finding it difficult to concentrate. However, research suggests that short breaks can improve both attention and memory.",
      ["When we focus on one task for a long time, our minds gradually become less active. We may continue reading or writing, but we stop noticing mistakes and begin to understand less of what we see. ", 1, " A brief pause can help us return to the task with more energy and a clearer idea of what still needs to be done."],
      ["The type of break is important. Checking messages may feel relaxing, but it can introduce new information and make it harder to focus again. ", 2, " Activities such as stretching, walking around the room or getting a drink are often better choices because they rest the mind without filling it with another task."],
      ["Breaks should also be planned carefully. If students stop every few minutes, they may never become fully involved in the work. ", 3, " Some people find that working for about twenty-five minutes and then resting for five minutes is useful, while others prefer longer periods of study."],
      ["Longer breaks can help after a more demanding period of work. For example, after completing a difficult chapter, a student might go outside for a short walk. ", 4, " Physical movement can reduce stress and give the mind time to organise new information before the next study period begins."],
      ["However, breaks are not a solution to every problem. If a student does not understand the task, resting will not provide the missing knowledge. ", 5, " In that situation, asking a teacher or classmate for help is likely to be more effective than repeatedly returning to the same confusing instructions."],
      ["The main point is that good studying depends on balance. Working continuously can reduce concentration, but taking too many breaks can waste time. ", 6, " Students should experiment and find a routine that helps them remain focused without becoming exhausted. The best system is one that can be followed regularly, not just for a single afternoon."],
    ],
  },
  "b2-pilot-1": {
    title: "Walking Meetings", heading: "Should meetings take place while walking?",
    sentences: { A: "The aim is not to turn every meeting into a form of exercise.", B: "Those who walked produced more ideas, and their suggestions were judged to be more original.", C: "Some managers worry that employees will not take a discussion seriously if it happens outside the office.", D: "This can make the arrangement feel fairer and prevent walking from becoming an expectation.", E: "Walking side by side also means they do not have to maintain eye contact throughout.", F: "A walking discussion may also be difficult if someone needs to write a formal record of decisions.", G: "For this reason, it is usually better to choose a simple route with little traffic." },
    answers: { 1: "E", 2: "B", 3: "G", 4: "F", 5: "D", 6: "A" },
    rationales: { 1: "This develops the comparison with an interview: reduced eye contact can make a difficult conversation feel less intense.", 2: "This supplies the result of the study introduced immediately before the gap.", 3: "Traffic, noise and complicated directions explain why a simple route is preferable; the next sentence gives suitable examples.", 4: "Taking a formal written record is another task that is difficult to complete while walking.", 5: "Offering a seated alternative makes the arrangement more inclusive and prevents walking from becoming an expectation.", 6: "This clarifies the balanced conclusion that walking should be one meeting option, not a rule." },
    paragraphs: [
      "Meetings are often held around a table, even when no screens, documents or equipment are needed. Recently, however, some companies have encouraged staff to discuss certain topics while walking. Supporters say this can improve both health and conversation, although it clearly does not suit every meeting.",
      ["Walking can reduce some of the pressure people feel in a formal room. When two colleagues move in the same direction, the discussion may feel less like an interview. ", 1, " This can help when people are discussing a difficult subject or trying to build a better working relationship."],
      ["There may also be benefits for creative thinking. In one study, participants completed idea-generating tasks either while sitting or walking. ", 2, " Researchers suggested that physical movement may help the mind move more freely between possibilities. This does not mean every walk produces brilliant ideas, but it may help a team consider new approaches."],
      ["The surroundings matter. A busy street can make it difficult to hear, while complicated directions may take attention away from the discussion. ", 3, " A quiet park, a familiar route around the building or even a large indoor space can work well."],
      ["Walking meetings are unsuitable for some tasks. If participants need to compare figures, take detailed notes or examine a plan, sitting at a table is more practical. ", 4, " The same is true when several people must join online or when the weather would make the experience uncomfortable."],
      ["Accessibility must be considered as well. Not everyone can walk easily or at the same speed, and nobody should feel required to explain a health condition. Organisers should offer an equally acceptable seated alternative. ", 5, " The value comes from creating a setting in which everyone can contribute comfortably."],
      ["Walking meetings are therefore best treated as one option among many. ", 6, " Used occasionally and for the right purpose, they can add variety, encourage movement and change the mood of a conversation. Used without thought, they may simply make an ordinary meeting less convenient."],
    ],
  },
  "b2-pilot-2": {
    title: "Repair Cafés", heading: "Repair cafes",
    sentences: { A: "Visitors are expected to take part rather than simply leave the item and collect it later.", B: "As a result, a successful event depends as much on communication as on technical skill.", C: "Organisers usually ask local businesses to donate old items for the volunteers to practise on.", D: "In some cases, therefore, the safest decision is to stop and advise the owner to replace it.", E: "This saves materials and energy that would be needed to manufacture and transport a replacement.", F: "Their aim is not to compete with trained specialists who depend on repair work for their income.", G: "This is especially useful because many people have lost confidence in attempting even basic repairs." },
    answers: { 1: "E", 2: "A", 3: "G", 4: "D", 5: "F", 6: "B" },
    rationales: { 1: "This explains the environmental benefit of keeping products in use instead of manufacturing replacements.", 2: "This establishes that visitors participate actively before the following examples of how they help.", 3: "This links people's lack of practical experience with the value of learning from a volunteer.", 4: "This follows the safety risks and unavailable parts; the next sentence reinforces the need to refuse unsafe repairs.", 5: "This answers the concern that repair cafes compete with businesses and leads into the referral to specialists.", 6: "This concludes that patient explanations and sensitive treatment matter as much as technical knowledge." },
    paragraphs: [
      "When a toaster, lamp or radio stops working, many people replace it immediately. Repair cafes offer another possibility. At these community events, visitors bring damaged objects and work with volunteers who try to repair them. The idea began in the Netherlands and has spread.",
      ["Repair cafes can reduce waste and extend the life of products with surprisingly small faults. ", 1, " A loose wire or worn part may stop a device that could otherwise work for years."],
      ["The events are not ordinary repair shops. Visitors are usually asked to sit with the volunteer and help where possible. ", 2, " Someone may hold a torch, remove screws or learn how to test an electrical connection. The purpose is partly to repair the object and partly to share knowledge."],
      ["Many adults have never been shown how household objects work and feel nervous about opening them. ", 3, " Watching an experienced volunteer can make future problems seem less mysterious, and some visitors later return to help others."],
      ["Not every object can be saved. Parts may be unavailable, or the damage may be too serious. Electrical items must also be checked carefully because an unsafe repair can cause injury or fire. ", 4, " A useful event therefore needs volunteers willing to say when a repair should not be attempted."],
      ["Professional repairers sometimes worry that free events will take customers away from local businesses. Organisers argue that they mainly deal with objects people would otherwise throw away. ", 5, " Some cafes recommend nearby specialists when a job requires professional tools or qualifications."],
      ["The social side is another part of their success. Volunteers need patience when explaining unfamiliar ideas, and visitors may arrive disappointed. ", 6, " A repaired lamp is satisfying, but so is a visitor leaving with more confidence and a better understanding of what is inside it."],
      "Repair cafes cannot solve the wider problem of products designed with parts that cannot be replaced. However, they challenge the idea that broken objects are automatically useless. By making practical skills visible, they encourage repair as a normal choice.",
    ],
  },
};
const formatTime = (seconds) => `${String(Math.floor(Math.max(0, seconds) / 60)).padStart(2, "0")}:${String(Math.max(0, seconds) % 60).padStart(2, "0")}`;

export default function OteGeneralReadingPart3Practice({ user, nativeRoutes = false }) {
  const navigate = useNavigate();
  const { setId = "b2-pilot-1" } = useParams();
  const task = tasks[setId] || tasks["b2-pilot-1"];
  const menuPath = getSitePath(nativeRoutes ? "/reading/general/part-3-gapped-text" : "/ote/reading/general/part-3-gapped-text");
  const [phase, setPhase] = useState("ready"); const [placements, setPlacements] = useState({}); const [selected, setSelected] = useState(""); const [secondsLeft, setSecondsLeft] = useState(TIME_SECONDS); const logged = useRef(false);
  const placedCount = Object.keys(placements).length;
  const score = useMemo(() => Object.entries(task.answers).reduce((total, [gap, answer]) => total + (placements[gap] === answer ? 1 : 0), 0), [placements, task.answers]);
  const available = Object.keys(task.sentences).filter((id) => !Object.values(placements).includes(id));
  useEffect(() => { if (user?.oteVersion === "advanced" || phase !== "active") return undefined; if (secondsLeft <= 0) { checkAnswers("time"); return undefined; } const timer = window.setTimeout(() => setSecondsLeft((current) => current - 1), 1000); return () => window.clearTimeout(timer); }, [phase, secondsLeft, user?.oteVersion]);
  const start = () => { logged.current = false; setPlacements({}); setSelected(""); setSecondsLeft(TIME_SECONDS); setPhase("active"); logOteTrainingStarted({ section: "reading", part: "part-3", mode: "timed_practice", taskId: `general-reading-part-3-${setId}`, taskTitle: `General Reading Part 3 ${task.title}`, variant: "general" }); };
  const place = (gap, id) => { if (phase !== "active" || !id) return; setPlacements((current) => ({ ...current, [gap]: id })); setSelected(""); };
  const clear = (gap) => { if (phase !== "active") return; setPlacements((current) => { const next = { ...current }; delete next[gap]; return next; }); };
  const record = (reason) => { if (logged.current) return; logged.current = true; logOteTrainingCompleted({ section: "reading", part: "part-3", mode: "timed_practice", taskId: `general-reading-part-3-${setId}`, taskTitle: `General Reading Part 3 ${task.title}`, variant: "general", score, total: 6, reason }); };
  function checkAnswers(reason = "checked") { setPhase("review"); record(reason); }
  if (user?.oteVersion === "advanced") return <Unavailable onBack={() => navigate(getSitePath(nativeRoutes ? "/reading" : "/ote/reading"))} />;
  return <main className="ote-training-page ote-reading-practice-page ote-reading-gapped-page"><Seo title="OTE General Reading Part 3 Timed Practice | Seif English" description="Timed General OTE Reading Part 3 gapped-text practice." /><button className="ote-training-back" type="button" onClick={() => navigate(menuPath)}><ArrowLeft size={18} /> Back to Part 3</button><header className="ote-training-hero"><p className="ote-kicker">General Reading Part 3</p><h1>{task.title}</h1><p>Insert the six missing sentences into the text. One sentence is extra.</p></header>{phase === "active" ? <div className="ote-writing-floating-timer"><Clock3 size={20} /><strong>{formatTime(secondsLeft)}</strong><span>Gapped text</span></div> : null}<section className="ote-practice-runner"><div className="ote-practice-progress"><div><span>{phase === "complete" ? "Complete" : phase === "review" ? "Answers checked" : `${placedCount} of 6 gaps filled`}</span><strong>{phase === "active" ? "11 minutes for the full task" : `${score} / 6 correct`}</strong></div><div className="ote-practice-progress-bar"><span style={{ width: `${phase === "active" ? (placedCount / 6) * 100 : 100}%` }} /></div></div>{phase === "ready" ? <ReadyCard user={user} onStart={start} /> : phase === "complete" ? <CompleteCard task={task} placements={placements} score={score} onRetry={start} onBack={() => navigate(menuPath)} /> : <article className="ote-practice-task-card ote-reading-gapped-task"><div className="ote-recorder-top"><div><p className="ote-kicker">Gapped text</p><h2>Drag a sentence into each gap</h2></div><div className="ote-recorder-timer is-recording"><Clock3 size={22} /><strong>{formatTime(secondsLeft)}</strong><span>{phase === "review" ? "Checked" : "Remaining"}</span></div></div><div className="ote-reading-gapped-layout"><SentenceBank available={available} selected={selected} setSelected={setSelected} sentences={task.sentences} /><Article task={task} placements={placements} selected={selected} place={place} clear={clear} reviewed={phase === "review"} /></div><div className="ote-recorder-actions">{phase === "review" ? <button type="button" onClick={() => setPhase("complete")}>View final report</button> : <button type="button" disabled={placedCount !== 6} onClick={() => checkAnswers()}>Check answers</button>}</div></article>}</section></main>;
}

function SentenceBank({ available, selected, setSelected, sentences }) { return <aside className="ote-gapped-sentence-bank"><div><p className="ote-kicker">Missing sentences</p><h2>Choose or drag</h2></div>{available.map((id) => <button key={id} type="button" draggable className={selected === id ? "is-selected" : ""} onDragStart={(event) => event.dataTransfer.setData("text/plain", id)} onClick={() => setSelected(selected === id ? "" : id)}><GripVertical size={18} /><strong>{id}</strong><span>{sentences[id]}</span></button>)}<p className="ote-gapped-extra">One sentence will remain unused.</p></aside>; }
function Article({ task, placements, selected, place, clear, reviewed }) { return <article className="ote-reading-gapped-text"><header><p className="ote-kicker">Article</p><h2>{task.heading}</h2></header>{task.paragraphs.map((paragraph, index) => Array.isArray(paragraph) ? <p key={index}>{paragraph[0]}<Gap id={String(paragraph[1])} task={task} placement={placements[paragraph[1]]} selected={selected} place={place} clear={clear} reviewed={reviewed} />{paragraph[2]}</p> : <p key={index}>{paragraph}</p>)}</article>; }
function Gap({ id, task, placement, selected, place, clear, reviewed }) { const correct = placement === task.answers[id]; return <span className={`ote-reading-gap ${placement ? "is-filled" : ""} ${reviewed ? (correct ? "is-correct" : "is-wrong") : ""}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); place(id, event.dataTransfer.getData("text/plain")); }}>{placement ? <span className="ote-reading-gap-answer"><strong>{placement}</strong> {task.sentences[placement]}{!reviewed ? <button type="button" onClick={() => clear(id)}><X size={15} /></button> : null}</span> : <button type="button" disabled={!selected || reviewed} onClick={() => place(id, selected)}>Gap {id}</button>}{reviewed ? <span className="ote-reading-gap-feedback"><strong>{correct ? "Correct." : `Answer: ${task.answers[id]}.`}</strong> {task.rationales[id]}</span> : null}</span>; }
function ReadyCard({ user, onStart }) { return <article className="ote-practice-task-card ote-reading-ready-card"><div className="ote-recorder-top"><div><p className="ote-kicker">Ready to start</p><h2>Timed gapped text</h2></div><div className="ote-recorder-timer is-ready"><Clock3 size={22} /><strong>11:00</strong><span>Full task</span></div></div><div className="ote-training-rule-grid"><article><h3>Six gaps</h3><p>Place six sentences into the text.</p></article><article><h3>One extra sentence</h3><p>One of the seven options is not needed.</p></article><article><h3>Review after checking</h3><p>Check all placements together, then review each link.</p></article></div>{!user ? <p className="ote-warning">Sign in to save this completed practice set to your progress.</p> : null}<div className="ote-recorder-actions"><button type="button" onClick={onStart}><Clock3 size={18} /> Start timed practice</button></div></article>; }
function CompleteCard({ task, placements, score, onRetry, onBack }) { return <section className="ote-practice-complete ote-reading-native-complete"><CheckCircle2 size={38} /><div><p className="ote-kicker">{task.title} complete</p><h2>{score} / 6</h2><p>{score === 6 ? "Excellent work. Every placement was correct." : "Review the gap-by-gap explanations below."}</p><div className="ote-reading-review-list">{Object.keys(task.answers).map((gap) => <article className={placements[gap] === task.answers[gap] ? "is-correct" : "is-wrong"} key={gap}><div><strong>Gap {gap}</strong><span>{placements[gap] === task.answers[gap] ? "Correct" : "Review"}</span></div><p><b>Answer:</b> {task.answers[gap]}. {task.sentences[task.answers[gap]]}</p><p>{task.rationales[gap]}</p></article>)}</div><div className="ote-complete-actions"><button type="button" onClick={onBack}>Back to Part 3</button><button type="button" onClick={onRetry}><RotateCcw size={18} /> Try again</button></div></div></section>; }
function Unavailable({ onBack }) { return <main className="ote-training-page"><button className="ote-training-back" type="button" onClick={onBack}><ArrowLeft size={18} /> Back to reading</button><header className="ote-training-hero"><p className="ote-kicker">General Reading Part 3</p><h1>Practice not available</h1><p>This timed set is available in the General OTE workspace.</p></header></main>; }
